import icon from './assets/profile-icon.png'

// const users  = [
//     {
//         uid: 1,
//         profile_image: icon,
//         name: 'Sharjeel Hussain',
//         phone: "03252105103",
//         email: "sharjeel@gmail.com",
//         subscriptionPlan: "annual", // annual, monthly, 
//     }
// ]
const users = [
    {
        uid: 1,
        profile_image: icon,
        name: 'Sharjeel Hussain',
        phone: "03252105103",
        email: "sharjeel@gmail.com",
        subscriptionPlan: "annual", // annual, monthly
    },
    {
        uid: 2,
        profile_image: icon,
        name: 'Ayesha Khan',
        phone: "03252345678",
        email: "ayesha.khan@example.com",
        subscriptionPlan: "monthly",
    },
    {
        uid: 3,
        profile_image: icon,
        name: 'Ahmed Ali',
        phone: "03257654321",
        email: "ahmed.ali@example.com",
        subscriptionPlan: "annual",
    },
    {
        uid: 4,
        profile_image: icon,
        name: 'Sara Malik',
        phone: "03251234567",
        email: "sara.malik@example.com",
        subscriptionPlan: "monthly",
    },
    {
        uid: 5,
        profile_image: icon,
        name: 'Bilal Siddiqui',
        phone: "03259876543",
        email: "bilal.siddiqui@example.com",
        subscriptionPlan: "annual",
    },
    {
        uid: 6,
        profile_image: icon,
        name: 'Hina Aslam',
        phone: "03253456789",
        email: "hina.aslam@example.com",
        subscriptionPlan: "monthly",
    },
    {
        uid: 7,
        profile_image: icon,
        name: 'Zain Ul Abidin',
        phone: "03257651234",
        email: "zain.abidin@example.com",
        subscriptionPlan: "annual",
    },
    {
        uid: 8,
        profile_image: icon,
        name: 'Mariam Raza',
        phone: "03253456987",
        email: "mariam.raza@example.com",
        subscriptionPlan: "monthly",
    },
    {
        uid: 9,
        profile_image: icon,
        name: 'Omar Farooq',
        phone: "03251239876",
        email: "omar.farooq@example.com",
        subscriptionPlan: "annual",
    },
    {
        uid: 10,
        profile_image: icon,
        name: 'Hassan Iqbal',
        phone: "03257658765",
        email: "hassan.iqbal@example.com",
        subscriptionPlan: "monthly",
    },
    {
        uid: 11,
        profile_image: icon,
        name: 'Nida Tariq',
        phone: "03252349876",
        email: "nida.tariq@example.com",
        subscriptionPlan: "annual",
    },
    {
        uid: 12,
        profile_image: icon,
        name: 'Usman Sheikh',
        phone: "03259872345",
        email: "usman.sheikh@example.com",
        subscriptionPlan: "monthly",
    },
    {
        uid: 13,
        profile_image: icon,
        name: 'Hira Qureshi',
        phone: "03257623489",
        email: "hira.qureshi@example.com",
        subscriptionPlan: "annual",
    },
    {
        uid: 14,
        profile_image: icon,
        name: 'Ali Haider',
        phone: "03252123987",
        email: "ali.haider@example.com",
        subscriptionPlan: "monthly",
    },
    {
        uid: 15,
        profile_image: icon,
        name: 'Fatima Khalid',
        phone: "03254321987",
        email: "fatima.khalid@example.com",
        subscriptionPlan: "annual",
    },
    {
        uid: 16,
        profile_image: icon,
        name: 'Kamran Javed',
        phone: "03257651923",
        email: "kamran.javed@example.com",
        subscriptionPlan: "monthly",
    },
    {
        uid: 17,
        profile_image: icon,
        name: 'Sana Ahmed',
        phone: "03251234987",
        email: "sana.ahmed@example.com",
        subscriptionPlan: "annual",
    },
    {
        uid: 18,
        profile_image: icon,
        name: 'Raza Shah',
        phone: "03254329871",
        email: "raza.shah@example.com",
        subscriptionPlan: "monthly",
    },
    {
        uid: 19,
        profile_image: icon,
        name: 'Amina Butt',
        phone: "03258764321",
        email: "amina.butt@example.com",
        subscriptionPlan: "annual",
    },
    {
        uid: 20,
        profile_image: icon,
        name: 'Fahad Khan',
        phone: "03257649871",
        email: "fahad.khan@example.com",
        subscriptionPlan: "monthly",
    },
    {
        uid: 21,
        profile_image: icon,
        name: 'Zara Saeed',
        phone: "03252348765",
        email: "zara.saeed@example.com",
        subscriptionPlan: "annual",
    }
];


export { users }